services:
#    acme_user.example:
#        class: Acme\UserBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]

    #EventListeners
    kernel.listener.security_listener:
        class: At21\EBoxOfficeBundle\EventListener\SecurityListener
        tags:
            - { name: kernel.event_listener, event: security.interactive_login, method: onSecurityInteractiveLogin }
        arguments: [@router, @security.context, @event_dispatcher]

    #Forms
    at21_eboxoffice.form.type.event:
        class: At21\EBoxOfficeBundle\Form\EventType
        tags:
            - { name: form.type, alias: event }

    at21_eboxoffice.form.type.theatre:
        class: At21\EBoxOfficeBundle\Form\TheatreType
        tags:
            - { name: form.type, alias: theatre }

    #Classes
    at21_eboxoffice_event:
        class: At21\EBoxOfficeBundle\Entity\Event
        arguments: []

    at21_eboxoffice_theatre:
        class: At21\EBoxOfficeBundle\Entity\Theatre
        arguments: []