services:
#    acme_user.example:
#        class: Acme\UserBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]

    #EventListeners
#    kernel.listener.security_listener:
#        class: At21\EBoxOfficeBundle\EventListener\SecurityListener
#        tags:
#            - { name: kernel.event_listener, event: security.interactive_login, method: onSecurityInteractiveLogin }
#        arguments: [@router, @security.context, @event_dispatcher]

    #Forms
    at21_eboxoffice.form.type.play:
        class: At21\EBoxOfficeBundle\Form\PlayType
        tags:
            - { name: form.type, alias: play }

    at21_eboxoffice.form.type.theatre:
        class: At21\EBoxOfficeBundle\Form\TheatreType
        tags:
            - { name: form.type, alias: theatre }

    at21_eboxoffice.form.type.session:
        class: At21\EBoxOfficeBundle\Form\SessionType
        tags:
            - { name: form.type, alias: session }

    #Classes
    at21_eboxoffice_boxoffice:
        class: At21\EBoxOfficeBundle\BoxOffice
        arguments:
            - @doctrine.orm.default_entity_manager

    at21_eboxoffice_play:
        class: At21\EBoxOfficeBundle\Entity\Play
        arguments: []

    at21_eboxoffice_theatre:
        class: At21\EBoxOfficeBundle\Entity\Theatre
        arguments: []

    at21_eboxoffice_session:
        class: At21\EBoxOfficeBundle\Entity\Session
        arguments: []

    at21_eboxoffice_seat:
        class: At21\EBoxOfficeBundle\Entity\Seat
        arguments: []

    #PayPal
    paypal_rest_paymentcontroller:
        class: At21\EBoxOfficeBundle\Controller\PaymentController
        arguments: ["@service_container", "@doctrine.orm.entity_manager"]

    paypal_rest_oauthtokencredential:
        class: PayPal\Auth\OAuthTokenCredential
        arguments: ["%paypal_rest_clientid%", "%paypal_rest_secret%"]

    paypal_rest_apicontext:
        class: PayPal\Rest\ApiContext
        arguments: ["@paypal_rest_oauthtokencredential"]

    paypal_rest_creditcard:
        class: PayPal\Api\CreditCard
        arguments: []

    paypal_rest_fundinginstrument:
        class: PayPal\Api\FundingInstrument
        arguments: []

    paypal_rest_payer:
        class: PayPal\Api\Payer
        arguments: []

    paypal_rest_item:
        class: PayPal\Api\Item
        arguments: []

    paypal_rest_itemlist:
        class: PayPal\Api\ItemList
        arguments: []

    paypal_rest_details:
        class: PayPal\Api\Details
        arguments: []

    paypal_rest_amount:
        class: PayPal\Api\Amount
        arguments: []

    paypal_rest_transaction:
        class: PayPal\Api\Transaction
        arguments: []

    paypal_rest_payment:
        class: PayPal\Api\Payment
        arguments: []