<?php

namespace At21\EBoxOfficeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SeatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SeatRepository extends EntityRepository
{
    /**
     * @param integer $eventId
     * @return array
     */
    public function getEventSeats($eventId)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT s FROM At21EBoxOfficeBundle:Seat s JOIN s.event e
                WHERE e.id = :eventId ORDER BY s.rowNumber, s.columnNumber'
            )
            ->setParameter('eventId', $eventId)
            ->getResult();
    }
}
