<?php

namespace At21\EBoxOfficeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SeatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SeatRepository extends EntityRepository
{
    /**
     * @param integer $id
     * @return array
     */
    public function findSeatsBySessionId($id)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT s FROM At21EBoxOfficeBundle:Seat s JOIN s.session se
                WHERE se.id = :id ORDER BY s.rowNumber, s.columnNumber'
            )
            ->setParameter('id', $id)
            ->getResult();
    }
}
