<?php

namespace At21\EBoxOfficeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SeatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SeatRepository extends EntityRepository
{
    /**
     * @param integer $sessionId
     * @return array
     */
    public function findSessionSeats($sessionId)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT s FROM At21EBoxOfficeBundle:Seat s JOIN s.session se
                WHERE se.id = :sessionId ORDER BY s.rowNumber, s.columnNumber'
            )
            ->setParameter('sessionId', $sessionId)
            ->getResult();
    }
}
