<?php

namespace At21\EBoxOfficeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SessionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SessionRepository extends EntityRepository
{
    /**
     * Find sessions by play id
     *
     * @param integer $id
     * @return array
     */
    public function findSessionsByPlayId($id)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT s FROM At21EBoxOfficeBundle:Session s JOIN At21EBoxOfficeBundle:Play p WHERE p.id = :id'
            )
            ->setParameter('id', $id)
            ->getResult();
    }
}
