<?php

namespace At21\EBoxOfficeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SessionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SessionRepository extends EntityRepository
{
    /**
     * Get sessions by play id
     *
     * @param integer $playId
     * @return array
     */
    public function findSessionsByPlayId($playId)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT s FROM At21EBoxOfficeBundle:Session s JOIN At21EBoxOfficeBundle:Play p WHERE p.id = :playId'
            )
            ->setParameter('playId', $playId)
            ->getResult();
    }

    /**
     * Get theatre
     *
     * @param integer $sessionId
     * @return array
     */
    public function getTheatre($sessionId)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT s FROM At21EBoxOfficeBundle:Session s WHERE s.id = :sessionId'
            )
            ->setParameter('sessionId', $sessionId)
            ->getResult();
    }
}
